      - name: Run download script
        env:
          SHAREPOINT_SITE_URL: ${{ secrets.SHAREPOINT_SITE_URL }}
          SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
          SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
          SHAREPOINT_FILE_URL: ${{ secrets.SHAREPOINT_FILE_URL }}
          LOCAL_SAVE_PATH: ${{ secrets.LOCAL_SAVE_PATH }}
        run: python download_sharepoint.py
